#!/bin/bash
PYFILE="$PYFILE"
PYFILEC="${PYFILE%.py}.pyc"

echo "Compiling $PYFILE ..."
python3 -m py_compile "$PYFILE"

if [ -f "__pycache__/$PYFILEC" ]; then
    mv "__pycache__/$PYFILEC" .
    rm -rf "__pycache__"
fi

